project:
  type: website
  output-dir: docs

website:
  title: "Israel Klebanoff"
  
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - icon: github
        href: https://github.com/IsraelKUARK
      
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    
editor: visual
